// <auto-generated />
using System;
using ExpensasAbbinatura.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpensasAbbinatura.Migrations
{
    [DbContext(typeof(ExpensasContext))]
    [Migration("20200623015244_add-building")]
    partial class addbuilding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExpensasAbbinatura.Models.Building", b =>
                {
                    b.Property<int>("BuildingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.HasKey("BuildingID");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Concept", b =>
                {
                    b.Property<int>("ConceptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ConceptTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("ConceptID");

                    b.HasIndex("ConceptTypeID");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.ConceptType", b =>
                {
                    b.Property<int>("ConceptTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("ConceptTypeID");

                    b.ToTable("ConceptTypes");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Installment", b =>
                {
                    b.Property<int>("InstallmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("StatusInstallmentStatusID")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime");

                    b.HasKey("InstallmentID");

                    b.HasIndex("PersonID");

                    b.HasIndex("StatusInstallmentStatusID");

                    b.ToTable("Installments");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.InstallmentConcept", b =>
                {
                    b.Property<int>("InstallmentConceptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<int?>("ConceptID")
                        .HasColumnType("int");

                    b.Property<int?>("InstallmentID")
                        .HasColumnType("int");

                    b.HasKey("InstallmentConceptID");

                    b.HasIndex("ConceptID");

                    b.HasIndex("InstallmentID");

                    b.ToTable("InstallmentConcepts");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.InstallmentStatus", b =>
                {
                    b.Property<string>("InstallmentStatusID")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("InstallmentStatusID");

                    b.ToTable("InstallmentStatus");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BuildingID")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("PersonID");

                    b.HasIndex("BuildingID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Concept", b =>
                {
                    b.HasOne("ExpensasAbbinatura.Models.ConceptType", "ConceptType")
                        .WithMany()
                        .HasForeignKey("ConceptTypeID");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Installment", b =>
                {
                    b.HasOne("ExpensasAbbinatura.Models.Person", "Person")
                        .WithMany("Installments")
                        .HasForeignKey("PersonID");

                    b.HasOne("ExpensasAbbinatura.Models.InstallmentStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusInstallmentStatusID");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.InstallmentConcept", b =>
                {
                    b.HasOne("ExpensasAbbinatura.Models.Concept", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptID");

                    b.HasOne("ExpensasAbbinatura.Models.Installment", null)
                        .WithMany("InstallmentConcepts")
                        .HasForeignKey("InstallmentID");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Person", b =>
                {
                    b.HasOne("ExpensasAbbinatura.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingID");
                });
#pragma warning restore 612, 618
        }
    }
}
