// <auto-generated />
using System;
using ExpensasAbbinatura.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpensasAbbinatura.Migrations
{
    [DbContext(typeof(ExpensasContext))]
    [Migration("20200612030356_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExpensasAbbinatura.Models.Concept", b =>
                {
                    b.Property<int>("ConceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ConceptTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("ConceptId");

                    b.HasIndex("ConceptTypeID");

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.ConceptType", b =>
                {
                    b.Property<int>("ConceptTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("ConceptTypeID");

                    b.ToTable("ConceptTypes");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Installment", b =>
                {
                    b.Property<int>("InstallmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime");

                    b.HasKey("InstallmentID");

                    b.HasIndex("PersonId");

                    b.ToTable("Installments");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.InstallmentConcept", b =>
                {
                    b.Property<int>("InstallmentConceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<int?>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int?>("InstallmentID")
                        .HasColumnType("int");

                    b.HasKey("InstallmentConceptId");

                    b.HasIndex("ConceptId");

                    b.HasIndex("InstallmentID");

                    b.ToTable("InstallmentConcepts");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Concept", b =>
                {
                    b.HasOne("ExpensasAbbinatura.Models.ConceptType", "ConceptType")
                        .WithMany()
                        .HasForeignKey("ConceptTypeID");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.Installment", b =>
                {
                    b.HasOne("ExpensasAbbinatura.Models.Person", null)
                        .WithMany("Installments")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("ExpensasAbbinatura.Models.InstallmentConcept", b =>
                {
                    b.HasOne("ExpensasAbbinatura.Models.Concept", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId");

                    b.HasOne("ExpensasAbbinatura.Models.Installment", null)
                        .WithMany("InstallmentConcepts")
                        .HasForeignKey("InstallmentID");
                });
#pragma warning restore 612, 618
        }
    }
}
