name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ExpensasAbbinatura.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ExpensasAbbinatura.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal ExpensasAbbinatura.csproj

  publish:
  
   runs-on: ubuntu-latest

   steps:
      - name: Publish
        run: dotnet publish --verbosity normal ExpensasAbbinatura.csproj
  
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'elmokono'
        server: '34.105.44.99'
        private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
        local_path: '/home/runner/work/expensas/expensas/bin/Debug/netcoreapp3.1/publish/*'
        remote_path: '/home/elmokono/www/publish/expensas'
        args: '-o ConnectTimeout=60'
